name: Check Links in README

on:
  push:
    paths:
      - 'README.md'

jobs:
  linkChecker:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lychee link checker
      run: cargo install lychee

    - name: Check links in README.md
      run: lychee --no-progress README.md
